---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
  namespace: vault-test3
spec:
  #storageClassName: "aws-efs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi